### ISSUE TITLE
Freeze at require statement

### ISSUE THREAD

**Issue by dyng** [treasure-data/td-client-ruby#8] opened 2013-10-01 11:59 UTC
I'm testing to use fluentd transferring data to TreasureData, by following [this](http://docs.fluentd.org/articles/http-to-td#fluentd-configuration) tutorial.

But I found fluentd freezed when it was trying to connect to TD, with single step debug I located where it stopped is `line 1509` in `td-client-ruby/lib/td/client/api.rb`. I'm not familiar with Ruby and can't figure out why it freezed. (At least everything works well when I define a same function `e` in a standalone script and call it.)

Here is my environment:
- Mac OS X v10.8.4
- ruby 1.9.3p448
- fluentd 0.10.39
- td-client 0.8.55

I worked around it by moving the require statement to `initialize`, but really want to know if I missed something.

**Comment by nahi** [comment] 2015-02-10 05:07
I'm closing this because it was not reproducible at that time, no additional report came and all requires moved to initialize by 75bceb3a.

**Closed by nahi** 2015-02-10 05:07 UTC
